HISTSIZE=1000
HISTFILESIZE=2000
HISTCONTROL=ignoreboth
PS1="\u@\h:\w\$ "
shopt -s histappend
shopt -s checkwinsize
shopt -s globstar

unalias -a

. $IDF_PATH/export.sh

export IDF_PATH
export ESPTOOL_PORT
export ESPTOOL_BAUD

